baseURL = 'https://pory-gone.github.io/'
languageCode = 'en'
title = 'PORYGON.ZONE'

[params]
  description = 'Blog, Portfolio & Chaos Zone - A glitchy digital playground'
  author = 'Porygone'
  dateFormat = 'January 2, 2006'
  
[params.social]
  github = 'pory-gone'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    name = 'Portfolio'
    url = '/projects/'
    weight = 3
  [[menu.main]]
    name = 'Chaos Zone'
    url = '/chaos/'
    weight = 4
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 5

[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = true
