baseURL = 'https://porygone.github.io/'
languageCode = 'it'
title = 'Il Mio Blog Personale'

[params]
  description = 'Blog personale - Pensieri, progetti e idee'
  author = 'Porygone'
  dateFormat = '2 January 2006'
  
[params.social]
  github = 'porygone'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 3

[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = true
